version: '3'
services:
  auth-service:
    image: skeet15/auth-vivelibre
    container_name: auth-service
    ports:
      - "8081:8081"
  app-service:
    build:
      context: .
    container_name: vivelibre-app
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
    environment:
      - AUTH_SERVICE_URL=http://localhost:8081/token

